document.writeln("<nav class=\'navbar navbar-expand-lg navbar-light bg-light\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <a class=\'navbar-brand\' href=\'./admin.html\'>Admin</a>");
document.writeln("            <button class=\'navbar-toggler\' type=\'button\' data-bs-toggle=\'collapse\' data-bs-target=\'#navbarText\'");
document.writeln("                aria-controls=\'navbarText\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("                <span class=\'navbar-toggler-icon\'></span>");
document.writeln("            </button>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbarText\'>");
document.writeln("                <ul class=\'navbar-nav me-auto mb-2 mb-lg-0\'>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link active\' aria-current=\'page\' href=\'./admin.html\'>Admin</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\' href=\'./admin/recommend.html\'>推荐</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\' href=\'./admin/note.html\'>笔记</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\' href=\'./admin/daily.html\'>日常</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <a class=\'nav-link\' href=\'./admin/daily.html\'>");
document.writeln("                    <span class=\'navbar-text\'>退出</span>");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");